services:
  postgres:
    image: postgres:15-alpine
    container_name: bus_system_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bus_system_rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: bus_system_keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  postgres_data:
