// <auto-generated />
using System;
using BusProvider.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusProvider.Infrastructure.Migrations
{
    [DbContext(typeof(BusProviderDbContext))]
    partial class BusProviderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusProvider.Domain.Aggregates.BusAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.HasKey("Id");

                    b.ToTable("buses", (string)null);
                });

            modelBuilder.Entity("BusProvider.Domain.Aggregates.BusProviderAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("bus_providers", (string)null);
                });

            modelBuilder.Entity("BusProvider.Domain.Aggregates.RouteAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uuid")
                        .HasColumnName("bus_id");

                    b.HasKey("Id");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("BusProvider.Domain.Aggregates.ScheduleAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uuid")
                        .HasColumnName("bus_id");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.HasKey("Id");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("BusProvider.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("BusProvider.Domain.Aggregates.BusAggregate", b =>
                {
                    b.OwnsOne("BusProvider.Domain.ValueObjects.SeatCapacity", "SeatCapacity", b1 =>
                        {
                            b1.Property<Guid>("BusAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("seat_capacity");

                            b1.HasKey("BusAggregateId");

                            b1.ToTable("buses");

                            b1.WithOwner()
                                .HasForeignKey("BusAggregateId");
                        });

                    b.OwnsOne("BusProvider.Domain.ValueObjects.BusNumber", "BusNumber", b1 =>
                        {
                            b1.Property<Guid>("BusAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("bus_number");

                            b1.HasKey("BusAggregateId");

                            b1.ToTable("buses");

                            b1.WithOwner()
                                .HasForeignKey("BusAggregateId");
                        });

                    b.OwnsOne("BusProvider.Domain.ValueObjects.BusType", "BusType", b1 =>
                        {
                            b1.Property<Guid>("BusAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("bus_type");

                            b1.HasKey("BusAggregateId");

                            b1.ToTable("buses");

                            b1.WithOwner()
                                .HasForeignKey("BusAggregateId");
                        });

                    b.Navigation("BusNumber")
                        .IsRequired();

                    b.Navigation("BusType")
                        .IsRequired();

                    b.Navigation("SeatCapacity")
                        .IsRequired();
                });

            modelBuilder.Entity("BusProvider.Domain.Aggregates.BusProviderAggregate", b =>
                {
                    b.OwnsOne("BusProvider.Domain.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("BusProviderAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("address");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("phone_number");

                            b1.HasKey("BusProviderAggregateId");

                            b1.ToTable("bus_providers");

                            b1.WithOwner()
                                .HasForeignKey("BusProviderAggregateId");
                        });

                    b.OwnsOne("BusProvider.Domain.ValueObjects.ProviderEmail", "Email", b1 =>
                        {
                            b1.Property<Guid>("BusProviderAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.HasKey("BusProviderAggregateId");

                            b1.ToTable("bus_providers");

                            b1.WithOwner()
                                .HasForeignKey("BusProviderAggregateId");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("BusProvider.Domain.Aggregates.RouteAggregate", b =>
                {
                    b.OwnsOne("BusProvider.Domain.ValueObjects.Location", "End", b1 =>
                        {
                            b1.Property<Guid>("RouteAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("end_location");

                            b1.HasKey("RouteAggregateId");

                            b1.ToTable("routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteAggregateId");
                        });

                    b.OwnsOne("BusProvider.Domain.ValueObjects.Location", "Start", b1 =>
                        {
                            b1.Property<Guid>("RouteAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("start_location");

                            b1.HasKey("RouteAggregateId");

                            b1.ToTable("routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteAggregateId");
                        });

                    b.OwnsOne("BusProvider.Domain.ValueObjects.Distance", "Distance", b1 =>
                        {
                            b1.Property<Guid>("RouteAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Kilometers")
                                .HasColumnType("double precision")
                                .HasColumnName("distance_km");

                            b1.HasKey("RouteAggregateId");

                            b1.ToTable("routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteAggregateId");
                        });

                    b.Navigation("Distance")
                        .IsRequired();

                    b.Navigation("End")
                        .IsRequired();

                    b.Navigation("Start")
                        .IsRequired();
                });

            modelBuilder.Entity("BusProvider.Domain.Aggregates.ScheduleAggregate", b =>
                {
                    b.OwnsOne("BusProvider.Domain.ValueObjects.TravelTime", "Arrival", b1 =>
                        {
                            b1.Property<Guid>("ScheduleAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<TimeOnly>("Value")
                                .HasColumnType("time without time zone")
                                .HasColumnName("arrival_time");

                            b1.HasKey("ScheduleAggregateId");

                            b1.ToTable("schedules");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleAggregateId");
                        });

                    b.OwnsOne("BusProvider.Domain.ValueObjects.TravelTime", "Departure", b1 =>
                        {
                            b1.Property<Guid>("ScheduleAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<TimeOnly>("Value")
                                .HasColumnType("time without time zone")
                                .HasColumnName("departure_time");

                            b1.HasKey("ScheduleAggregateId");

                            b1.ToTable("schedules");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleAggregateId");
                        });

                    b.OwnsOne("BusProvider.Domain.ValueObjects.SeatCapacity", "SeatsAvailable", b1 =>
                        {
                            b1.Property<Guid>("ScheduleAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("seats_available");

                            b1.HasKey("ScheduleAggregateId");

                            b1.ToTable("schedules");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleAggregateId");
                        });

                    b.OwnsOne("BusProvider.Domain.ValueObjects.TravelDate", "TripDate", b1 =>
                        {
                            b1.Property<Guid>("ScheduleAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("trip_date");

                            b1.HasKey("ScheduleAggregateId");

                            b1.ToTable("schedules");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleAggregateId");
                        });

                    b.Navigation("Arrival")
                        .IsRequired();

                    b.Navigation("Departure")
                        .IsRequired();

                    b.Navigation("SeatsAvailable")
                        .IsRequired();

                    b.Navigation("TripDate")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
